name: feast

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      FEAST_SECRET: ${{secrets.FEAST_SECRET}}
      FEAST_TOKEN: ${{secrets.FEAST_TOKEN

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Print envs
        run: go run feast/feast.go
